export const SMTableData = [
    {
        node: "뉴턴홀",
        average: "23",
        Jan: "23",
        Feb: "",
        Mar: "",
        Apr: "",
        May: "",
        Jun: "",
        Jul: "",
        Aug: "",
        Sep: "",
        Oct: "",
        Nov: "",
        Dec: ""
    },
    {
        node: "그레이스홀",
        average: "21",
        Jan: "21",
        Feb: "",
        Mar: "",
        Apr: "",
        May: "",
        Jun: "",
        Jul: "",
        Aug: "",
        Sep: "",
        Oct: "",
        Nov: "",
        Dec: ""
    },
    {
        node: "그레이스홀",
        average: "21",
        Jan: "21",
        Feb: "",
        Mar: "",
        Apr: "",
        May: "",
        Jun: "",
        Jul: "",
        Aug: "",
        Sep: "",
        Oct: "",
        Nov: "",
        Dec: ""
    },
    {
        node: "현동홀",
        average: "25",
        Jan: "25",
        Feb: "",
        Mar: "",
        Apr: "",
        May: "",
        Jun: "",
        Jul: "",
        Aug: "",
        Sep: "",
        Oct: "",
        Nov: "",
        Dec: ""
    },
    {
        node: "오석관",
        average: "28",
        Jan: "28",
        Feb: "",
        Mar: "",
        Apr: "",
        May: "",
        Jun: "",
        Jul: "",
        Aug: "",
        Sep: "",
        Oct: "",
        Nov: "",
        Dec: ""
    },

]